import json
import re
from pathlib import Path


class JavaGenerator:
    """
    Application-independent Java generator.

    It does NOT hardcode business module names.

    It reads analysis_report.json and generates:
      - ExecutionContext.java
      - ModuleResult.java
      - AssemblerModule.java
      - ModernizationRuntime.java
      - One Java class per discovered HLASM module
    """

    def __init__(self, report_path="analysis_report.json", output_dir="generated_java"):
        self.report_path = report_path
        self.output_dir = Path(output_dir)
        self.report = self._load_report()

    def _load_report(self):
        with open(self.report_path, "r", encoding="utf-8") as f:
            return json.load(f)

    def generate(self):
        self.output_dir.mkdir(parents=True, exist_ok=True)

        # Clean old generated Java files so old hardcoded files do not remain.
        for old_file in self.output_dir.glob("*.java"):
            old_file.unlink()

        modules = self._discover_modules()

        print("Discovered modules for Java generation:")
        for module in modules:
            print(f"  - {module}")

        self._write("ExecutionContext.java", self._execution_context())
        self._write("ModuleResult.java", self._module_result())
        self._write("AssemblerModule.java", self._assembler_module())
        self._write("ModernizationRuntime.java", self._runtime(modules))

        for module in modules:
            class_name = self._to_class_name(module)
            self._write(
                f"{class_name}.java",
                self._module_class(module, class_name),
            )

        print(f"\nGenerated Java files in: {self.output_dir}")

    def _discover_modules(self):
        """
        Discover modules from every section of analysis_report.json.

        This avoids hardcoding module names and works for future applications.
        """

        modules = set()

        # Sections where module names are dictionary keys.
        module_key_sections = [
            "reads",
            "writes",
            "return_codes",
            "conditions",
            "module_parameter_context",
            "register_map",
            "record_buffer_reads",
            "record_buffer_writes",
            "condition_branches",
        ]

        for section in module_key_sections:
            value = self.report.get(section, {})
            if isinstance(value, dict):
                for module in value.keys():
                    if module:
                        modules.add(module.upper())

        # Symbols contain module names inside each symbol record.
        symbols = self.report.get("symbols", {})
        if isinstance(symbols, dict):
            for _, info in symbols.items():
                if isinstance(info, dict):
                    module = info.get("module")
                    if module:
                        modules.add(module.upper())

        # DDNAME / ACB definitions contain module names.
        ddnames = self.report.get("ddnames", {})
        if isinstance(ddnames, dict):
            for _, info in ddnames.items():
                if isinstance(info, dict):
                    module = info.get("module")
                    if module:
                        modules.add(module.upper())

        # RPL definitions contain module names.
        rpl_areas = self.report.get("rpl_areas", {})
        if isinstance(rpl_areas, dict):
            for _, info in rpl_areas.items():
                if isinstance(info, dict):
                    module = info.get("module")
                    if module:
                        modules.add(module.upper())

        # Fallback: if report has a direct modules list in the future.
        direct_modules = self.report.get("modules", [])
        if isinstance(direct_modules, list):
            for module in direct_modules:
                if module:
                    modules.add(str(module).upper())

        return sorted(modules)

    def _to_class_name(self, module_name):
        """
        Convert HLASM module name to Java class name.

        Examples:
          MAINDRV  -> Maindrv
          CUSTVAL  -> Custval
          PAYROLL01 -> Payroll01
        """

        parts = re.split(r"[^A-Za-z0-9]+", module_name.lower())
        class_name = "".join(part.capitalize() for part in parts if part)

        if not class_name:
            class_name = "GeneratedModule"

        if class_name[0].isdigit():
            class_name = "Module" + class_name

        return class_name

    def _write(self, filename, content):
        path = self.output_dir / filename
        path.write_text(content.strip() + "\n", encoding="utf-8")

    def _header(self, name):
        return f"""
/*
 * Generated by Legacy Assembler Modernization Intelligence Platform.
 *
 * Generated artifact: {name}
 *
 * This is an application-independent Java replacement candidate.
 * Review analyzer notes before production use.
 */
"""

    def _execution_context(self):
        return self._header("ExecutionContext") + """
import java.math.BigDecimal;
import java.util.HashMap;
import java.util.Map;

public class ExecutionContext {

    private final Map<String, Object> fields = new HashMap<>();

    public Object get(String fieldName) {
        return fields.get(fieldName);
    }

    public void set(String fieldName, Object value) {
        fields.put(fieldName, value);
    }

    public String getString(String fieldName) {
        Object value = fields.get(fieldName);
        return value == null ? "" : value.toString();
    }

    public void setString(String fieldName, String value) {
        fields.put(fieldName, value);
    }

    public BigDecimal getDecimal(String fieldName) {
        Object value = fields.get(fieldName);

        if (value == null) {
            return BigDecimal.ZERO;
        }

        if (value instanceof BigDecimal) {
            return (BigDecimal) value;
        }

        return new BigDecimal(value.toString());
    }

    public void setDecimal(String fieldName, BigDecimal value) {
        fields.put(fieldName, value);
    }

    public Map<String, Object> snapshot() {
        return new HashMap<>(fields);
    }
}
"""

    def _module_result(self):
        return self._header("ModuleResult") + """
public class ModuleResult {

    private final int returnCode;
    private final String message;

    public ModuleResult(int returnCode, String message) {
        this.returnCode = returnCode;
        this.message = message;
    }

    public int getReturnCode() {
        return returnCode;
    }

    public String getMessage() {
        return message;
    }

    public boolean isOk() {
        return returnCode == 0;
    }

    public static ModuleResult ok() {
        return new ModuleResult(0, "OK");
    }

    public static ModuleResult rc(int rc, String message) {
        return new ModuleResult(rc, message);
    }
}
"""

    def _assembler_module(self):
        return self._header("AssemblerModule") + """
public interface AssemblerModule {

    String name();

    ModuleResult execute(ExecutionContext ctx);
}
"""

    def _runtime(self, modules):
        registrations = []

        for module in modules:
            class_name = self._to_class_name(module)
            registrations.append(f"        modules.add(new {class_name}());")

        registrations_text = "\n".join(registrations)

        return self._header("ModernizationRuntime") + f"""
import java.util.ArrayList;
import java.util.List;

public class ModernizationRuntime {{

    private final List<AssemblerModule> modules = new ArrayList<>();

    public ModernizationRuntime() {{
{registrations_text}
    }}

    public List<ModuleResult> execute(ExecutionContext ctx) {{
        List<ModuleResult> results = new ArrayList<>();

        for (AssemblerModule module : modules) {{
            ModuleResult result = module.execute(ctx);
            results.add(result);

            if (!result.isOk()) {{
                break;
            }}
        }}

        return results;
    }}
}}
"""

    def _module_class(self, module, class_name):
        reads = self.report.get("reads", {}).get(module, [])
        writes = self.report.get("writes", {}).get(module, [])
        return_codes = self.report.get("return_codes", {}).get(module, [])
        conditions = self.report.get("conditions", {}).get(module, [])
        record_reads = self.report.get("record_buffer_reads", {}).get(module, [])
        record_writes = self.report.get("record_buffer_writes", {}).get(module, [])
        warnings = [
            warning
            for warning in self.report.get("warnings", [])
            if warning.startswith(module + ":")
        ]

        default_rc = "0"
        if return_codes:
            if "0" in return_codes:
                default_rc = "0"
            else:
                default_rc = str(return_codes[0])

        comment = self._module_comment(
            module=module,
            reads=reads,
            writes=writes,
            return_codes=return_codes,
            conditions=conditions,
            record_reads=record_reads,
            record_writes=record_writes,
            warnings=warnings,
        )

        generated_logic = self._generate_candidate_logic(
            module=module,
            reads=reads,
            writes=writes,
            conditions=conditions,
            return_codes=return_codes,
            record_reads=record_reads,
            record_writes=record_writes,
        )

        return self._header(class_name) + f"""
public class {class_name} implements AssemblerModule {{

    @Override
    public String name() {{
        return "{module}";
    }}

    @Override
    public ModuleResult execute(ExecutionContext ctx) {{

{comment}

{generated_logic}

        return ModuleResult.rc({default_rc}, "{module} executed as generated candidate");
    }}
}}
"""

    def _module_comment(
        self,
        module,
        reads,
        writes,
        return_codes,
        conditions,
        record_reads,
        record_writes,
        warnings,
    ):
        lines = []
        lines.append("        /*")
        lines.append(f"         * HLASM Module: {module}")
        lines.append("         *")

        if reads:
            lines.append("         * Business fields read:")
            for item in reads:
                lines.append(f"         *   - {item}")
            lines.append("         *")

        if writes:
            lines.append("         * Business fields written:")
            for item in writes:
                lines.append(f"         *   - {item}")
            lines.append("         *")

        if record_writes:
            lines.append("         * Record buffers written/populated:")
            for item in record_writes:
                lines.append(f"         *   - {item}")
            lines.append("         *")

        if record_reads:
            lines.append("         * Record buffers read/written out:")
            for item in record_reads:
                lines.append(f"         *   - {item}")
            lines.append("         *")

        if conditions:
            lines.append("         * Conditions detected:")
            for condition in conditions:
                instr = condition.get("instruction")
                operands = ", ".join(condition.get("operands", []))
                lines.append(f"         *   - {instr} {operands}")
            lines.append("         *")

        if return_codes:
            lines.append("         * Return codes detected:")
            for rc in return_codes:
                lines.append(f"         *   - RC={rc}")
            lines.append("         *")

        if warnings:
            lines.append("         * Analyzer warnings:")
            for warning in warnings:
                lines.append(f"         *   - {warning}")
            lines.append("         *")

        lines.append("         */")

        return "\n".join(lines)

    def _generate_candidate_logic(
        self,
        module,
        reads,
        writes,
        conditions,
        return_codes,
        record_reads,
        record_writes,
    ):
        """
        Global candidate logic.

        This does not hardcode business module names.
        It generates safe placeholder logic from analysis metadata.

        Future improvement:
          add instruction-level translator to replace TODOs with exact Java logic.
        """

        lines = []

        lines.append("        // Generated candidate logic from CFG/PDG metadata.")
        lines.append("        // This is application-independent and does not rely on hardcoded module names.")

        if record_writes:
            for buffer in record_writes:
                lines.append(f'        // Record buffer populated by legacy I/O: {buffer}')
                lines.append(f'        ctx.set("{buffer}", ctx.get("{buffer}"));')

        if record_reads:
            for buffer in record_reads:
                lines.append(f'        // Record buffer written out by legacy I/O: {buffer}')
                lines.append(f'        Object {buffer.lower()}Buffer = ctx.get("{buffer}");')

        if writes:
            for field in writes:
                lines.append(f'        // Field may be written by this module: {field}')
                lines.append(f'        // ctx.set("{field}", <translated-value>);')

        if conditions:
            lines.append("")
            lines.append("        // Conditions detected in assembler:")
            for condition in conditions:
                instr = condition.get("instruction")
                operands = condition.get("operands", [])
                operand_text = ", ".join(operands)
                lines.append(f'        // {instr} {operand_text}')

        lines.append("")
        lines.append("        // TODO: Add instruction-level translated Java logic here.")

        return "\n".join(lines)


if __name__ == "__main__":
    generator = JavaGenerator(
        report_path="analysis_report.json",
        output_dir="generated_java",
    )
    generator.generate()