/*
 * Generated by Legacy Assembler Modernization Intelligence Platform.
 * Artifact: AsmRuntime
 */

import java.math.BigDecimal;
import java.math.RoundingMode;

public class AsmRuntime {

    public static class ConditionCode {
        public static final int EQUAL = 0;
        public static final int LOW = 1;
        public static final int HIGH = 2;
        public static final int OVERFLOW = 3;

        private int value = EQUAL;

        public int get() {
            return value;
        }

        public void setEqual() {
            value = EQUAL;
        }

        public void setLow() {
            value = LOW;
        }

        public void setHigh() {
            value = HIGH;
        }

        public void setOverflow() {
            value = OVERFLOW;
        }
    }

    public static class Registers {
        private final int[] gpr = new int[16];

        public int get(int register) {
            return gpr[register];
        }

        public void set(int register, int value) {
            gpr[register] = value;
        }

        public void clear(int register) {
            gpr[register] = 0;
        }

        public void decrement(int register) {
            gpr[register] = gpr[register] - 1;
        }
    }

    public static class Memory {

        public static String normalize(String value, int length) {
            if (value == null) {
                value = "";
            }

            if (value.length() > length) {
                return value.substring(0, length);
            }

            return String.format("%-" + length + "s", value);
        }

        public static void mvc(ExecutionContext ctx, String target, int length, String source) {
            ctx.setString(target, normalize(ctx.getString(source), length));
        }

        public static void mvcLiteral(ExecutionContext ctx, String target, int length, String literal) {
            ctx.setString(target, normalize(literal, length));
        }

        public static void mvi(ExecutionContext ctx, String target, char value) {
            ctx.setString(target, String.valueOf(value));
        }

        public static int clc(ExecutionContext ctx, String left, int length, String right, ConditionCode cc) {
            String l = normalize(ctx.getString(left), length);
            String r = normalize(ctx.getString(right), length);
            int result = l.compareTo(r);
            setCompareCondition(result, cc);
            return result;
        }

        public static int clcLiteral(ExecutionContext ctx, String left, int length, String literal, ConditionCode cc) {
            String l = normalize(ctx.getString(left), length);
            String r = normalize(literal, length);
            int result = l.compareTo(r);
            setCompareCondition(result, cc);
            return result;
        }

        public static int cli(ExecutionContext ctx, String left, char literal, ConditionCode cc) {
            String value = ctx.getString(left);
            char first = value.isEmpty() ? 0 : value.charAt(0);
            int result = Character.compare(first, literal);
            setCompareCondition(result, cc);
            return result;
        }

        public static void xc(ExecutionContext ctx, String target, int length, String source) {
            byte[] left = normalize(ctx.getString(target), length).getBytes();
            byte[] right = normalize(ctx.getString(source), length).getBytes();
            byte[] out = new byte[length];

            for (int i = 0; i < length; i++) {
                out[i] = (byte) (left[i] ^ right[i]);
            }

            ctx.setString(target, new String(out));
        }

        private static void setCompareCondition(int result, ConditionCode cc) {
            if (result == 0) {
                cc.setEqual();
            } else if (result < 0) {
                cc.setLow();
            } else {
                cc.setHigh();
            }
        }
    }

    public static class Packed {

        public static void zap(
                ExecutionContext ctx,
                String target,
                String source,
                int targetDigits,
                int scale,
                ConditionCode cc) {

            BigDecimal value = ctx.getDecimal(source);
            BigDecimal normalized = fitPacked(value, targetDigits, scale);
            ctx.setDecimal(target, normalized);
            setDecimalCondition(normalized, cc);
        }

        public static void ap(
                ExecutionContext ctx,
                String target,
                String source,
                int targetDigits,
                int scale,
                ConditionCode cc) {

            BigDecimal result = ctx.getDecimal(target).add(ctx.getDecimal(source));
            result = fitPacked(result, targetDigits, scale);
            ctx.setDecimal(target, result);
            setDecimalCondition(result, cc);
        }

        public static void sp(
                ExecutionContext ctx,
                String target,
                String source,
                int targetDigits,
                int scale,
                ConditionCode cc) {

            BigDecimal result = ctx.getDecimal(target).subtract(ctx.getDecimal(source));
            result = fitPacked(result, targetDigits, scale);
            ctx.setDecimal(target, result);
            setDecimalCondition(result, cc);
        }

        public static void mp(
                ExecutionContext ctx,
                String target,
                String source,
                int targetDigits,
                int scale,
                ConditionCode cc) {

            BigDecimal result = ctx.getDecimal(target).multiply(ctx.getDecimal(source));
            result = fitPacked(result, targetDigits, scale);
            ctx.setDecimal(target, result);
            setDecimalCondition(result, cc);
        }

        public static void dp(
                ExecutionContext ctx,
                String target,
                String source,
                int targetDigits,
                int scale,
                ConditionCode cc) {

            BigDecimal divisor = ctx.getDecimal(source);

            if (BigDecimal.ZERO.compareTo(divisor) == 0) {
                throw new ArithmeticException("Packed decimal divide by zero");
            }

            BigDecimal result = ctx.getDecimal(target).divide(divisor, scale, RoundingMode.HALF_UP);
            result = fitPacked(result, targetDigits, scale);
            ctx.setDecimal(target, result);
            setDecimalCondition(result, cc);
        }

        public static int cp(ExecutionContext ctx, String left, String right, ConditionCode cc) {
            int result = ctx.getDecimal(left).compareTo(ctx.getDecimal(right));
            setCompareCondition(result, cc);
            return result;
        }

        public static BigDecimal fitPacked(BigDecimal value, int totalDigits, int scale) {
            BigDecimal scaled = value.setScale(scale, RoundingMode.HALF_UP);
            BigDecimal absolute = scaled.abs();

            String digitsOnly = absolute
                    .movePointRight(scale)
                    .toPlainString()
                    .replace(".", "");

            if (digitsOnly.length() > totalDigits) {
                throw new ArithmeticException(
                        "Packed decimal overflow: value=" + value + " totalDigits=" + totalDigits);
            }

            return scaled;
        }

        private static void setDecimalCondition(BigDecimal value, ConditionCode cc) {
            int result = value.compareTo(BigDecimal.ZERO);

            if (result == 0) {
                cc.setEqual();
            } else if (result < 0) {
                cc.setLow();
            } else {
                cc.setHigh();
            }
        }

        private static void setCompareCondition(int result, ConditionCode cc) {
            if (result == 0) {
                cc.setEqual();
            } else if (result < 0) {
                cc.setLow();
            } else {
                cc.setHigh();
            }
        }
    }

    public static class Register {

        public static void xr(Registers registers, int r1, int r2, ConditionCode cc) {
            int result = registers.get(r1) ^ registers.get(r2);
            registers.set(r1, result);
            setBinaryCondition(result, cc);
        }

        public static void sr(Registers registers, int r1, int r2, ConditionCode cc) {
            int result = registers.get(r1) - registers.get(r2);
            registers.set(r1, result);
            setBinaryCondition(result, cc);
        }

        public static void ar(Registers registers, int r1, int r2, ConditionCode cc) {
            int result = registers.get(r1) + registers.get(r2);
            registers.set(r1, result);
            setBinaryCondition(result, cc);
        }

        public static void ltr(Registers registers, int r1, int r2, ConditionCode cc) {
            int value = registers.get(r2);
            registers.set(r1, value);
            setBinaryCondition(value, cc);
        }

        public static void lh(Registers registers, int register, short halfword) {
            registers.set(register, halfword);
        }

        public static void l(Registers registers, int register, int fullword) {
            registers.set(register, fullword);
        }

        private static void setBinaryCondition(int value, ConditionCode cc) {
            if (value == 0) {
                cc.setEqual();
            } else if (value < 0) {
                cc.setLow();
            } else {
                cc.setHigh();
            }
        }
    }

    public static class Branch {

        public static boolean isEqual(ConditionCode cc) {
            return cc.get() == ConditionCode.EQUAL;
        }

        public static boolean isNotEqual(ConditionCode cc) {
            return cc.get() != ConditionCode.EQUAL;
        }

        public static boolean isLow(ConditionCode cc) {
            return cc.get() == ConditionCode.LOW;
        }

        public static boolean isHigh(ConditionCode cc) {
            return cc.get() == ConditionCode.HIGH;
        }

        public static boolean bct(Registers registers, int register) {
            registers.decrement(register);
            return registers.get(register) != 0;
        }

        public static boolean bctr(Registers registers, int register) {
            registers.decrement(register);
            return registers.get(register) != 0;
        }

        public static boolean isNotHigh(ConditionCode cc) {
            return cc.get() != ConditionCode.HIGH;
       }

        public static boolean isNotLow(ConditionCode cc) {
            return cc.get() != ConditionCode.LOW;
        }
    }
}
