/*
 * Generated by Legacy Assembler Modernization Intelligence Platform.
 * Artifact: AsmRuntime
 */

import java.math.BigDecimal;
import java.math.RoundingMode;

public class AsmRuntime {

    public static class ConditionCode {
        public static final int EQUAL = 0;
        public static final int LOW = 1;
        public static final int HIGH = 2;
        public static final int OVERFLOW = 3;

        private int value = EQUAL;

        public int get() {
            return value;
        }

        public void setEqual() {
            value = EQUAL;
        }

        public void setLow() {
            value = LOW;
        }

        public void setHigh() {
            value = HIGH;
        }

        public void setOverflow() {
            value = OVERFLOW;
        }
    }

    public static class Registers {
        private final int[] gpr = new int[16];

        public int get(int register) {
            return gpr[register];
        }

        public void set(int register, int value) {
            gpr[register] = value;
        }

        public void clear(int register) {
            gpr[register] = 0;
        }

        public void decrement(int register) {
            gpr[register] = gpr[register] - 1;
        }
    }

    public static class Memory {

        public static String normalize(String value, int length) {
            if (value == null) {
                value = "";
            }

            if (value.length() > length) {
                return value.substring(0, length);
            }

            return String.format("%-" + length + "s", value);
        }

        public static void mvc(ExecutionContext ctx, String target, int length, String source) {
            ctx.setString(target, normalize(ctx.getString(source), length));
        }

        public static void mvcLiteral(ExecutionContext ctx, String target, int length, String literal) {
            ctx.setString(target, normalize(literal, length));
        }

        public static void mvi(ExecutionContext ctx, String target, char value) {
            ctx.setString(target, String.valueOf(value));
        }

        public static int clc(ExecutionContext ctx, String left, int length, String right, ConditionCode cc) {
            String l = normalize(ctx.getString(left), length);
            String r = normalize(ctx.getString(right), length);
            int result = l.compareTo(r);
            setCompareCondition(result, cc);
            return result;
        }

        public static int clcLiteral(ExecutionContext ctx, String left, int length, String literal, ConditionCode cc) {
            String l = normalize(ctx.getString(left), length);
            String r = normalize(literal, length);
            int result = l.compareTo(r);
            setCompareCondition(result, cc);
            return result;
        }

        public static int cli(ExecutionContext ctx, String left, char literal, ConditionCode cc) {
            String value = ctx.getString(left);
            char first = value.isEmpty() ? 0 : value.charAt(0);
            int result = Character.compare(first, literal);
            setCompareCondition(result, cc);
            return result;
        }

        public static void xc(ExecutionContext ctx, String target, int length, String source) {
            byte[] left = normalize(ctx.getString(target), length).getBytes();
            byte[] right = normalize(ctx.getString(source), length).getBytes();
            byte[] out = new byte[length];

            for (int i = 0; i < length; i++) {
                out[i] = (byte) (left[i] ^ right[i]);
            }

            ctx.setString(target, new String(out));
        }

        public static void tr(ExecutionContext ctx, String target, int length, String tableField) {
            String input = normalize(ctx.getString(target), length);
            String table = ctx.getString(tableField);

            if (table == null || table.isEmpty()) {
                ctx.setString(target, input);
                return;
            }

            StringBuilder out = new StringBuilder();

            for (int i = 0; i < input.length(); i++) {
                int idx = input.charAt(i) & 0xFF;

                if (idx < table.length()) {
                    out.append(table.charAt(idx));
                } else {
                    out.append(input.charAt(i));
                }
            }

            ctx.setString(target, out.toString());
        }

        public static void trt(
                ExecutionContext ctx,
                String target,
                int length,
                String tableField,
                Registers registers,
                ConditionCode cc) {

            String input = normalize(ctx.getString(target), length);
            String table = ctx.getString(tableField);

            if (table == null || table.isEmpty()) {
                cc.setEqual();
                return;
            }

            for (int i = 0; i < input.length(); i++) {
                int idx = input.charAt(i) & 0xFF;

                if (idx < table.length() && table.charAt(idx) != 0 && table.charAt(idx) != '0') {
                    registers.set(1, i);
                    registers.set(2, table.charAt(idx));
                    cc.setLow();
                    return;
                }
            }

            cc.setEqual();
        }

        public static void oi(ExecutionContext ctx, String targetOperand, int immediate, ConditionCode cc) {
            applyImmediateLogical(ctx, targetOperand, immediate, "OR", cc);
        }

        public static void xi(ExecutionContext ctx, String targetOperand, int immediate, ConditionCode cc) {
            applyImmediateLogical(ctx, targetOperand, immediate, "XOR", cc);
        }

        public static void ni(ExecutionContext ctx, String targetOperand, int immediate, ConditionCode cc) {
            applyImmediateLogical(ctx, targetOperand, immediate, "AND", cc);
        }

        private static void applyImmediateLogical(
                ExecutionContext ctx,
                String targetOperand,
                int immediate,
                String operation,
                ConditionCode cc) {

            String field = targetOperand;
            int offset = 0;

            int plus = targetOperand.indexOf('+');
            if (plus >= 0) {
                field = targetOperand.substring(0, plus);
                try {
                    offset = Integer.parseInt(targetOperand.substring(plus + 1));
                } catch (NumberFormatException ex) {
                    offset = 0;
                }
            }

            String value = ctx.getString(field);
            if (value == null) {
                value = "";
            }
            if (value.length() <= offset) {
                value = Memory.normalize(value, offset + 1);
            }

            char[] chars = value.toCharArray();
            int current = chars[offset] & 0xFF;
            int result;

            if ("AND".equals(operation)) {
                result = current & immediate;
            } else if ("XOR".equals(operation)) {
                result = current ^ immediate;
            } else {
                result = current | immediate;
            }

            chars[offset] = (char) (result & 0xFF);
            ctx.setString(field, new String(chars));

            if ((result & 0xFF) == 0) {
                cc.setEqual();
            } else {
                cc.setLow();
            }
        }

        private static void setCompareCondition(int result, ConditionCode cc) {
            if (result == 0) {
                cc.setEqual();
            } else if (result < 0) {
                cc.setLow();
            } else {
                cc.setHigh();
            }
        }
    }

    public static class Packed {

        public static void zap(
                ExecutionContext ctx,
                String target,
                String source,
                int targetDigits,
                int scale,
                ConditionCode cc) {

            BigDecimal value = ctx.getDecimal(source);
            BigDecimal normalized = fitPacked(value, targetDigits, scale);
            ctx.setDecimal(target, normalized);
            setDecimalCondition(normalized, cc);
        }

        public static void ap(
                ExecutionContext ctx,
                String target,
                String source,
                int targetDigits,
                int scale,
                ConditionCode cc) {

            BigDecimal result = ctx.getDecimal(target).add(ctx.getDecimal(source));
            result = fitPacked(result, targetDigits, scale);
            ctx.setDecimal(target, result);
            setDecimalCondition(result, cc);
        }

        public static void sp(
                ExecutionContext ctx,
                String target,
                String source,
                int targetDigits,
                int scale,
                ConditionCode cc) {

            BigDecimal result = ctx.getDecimal(target).subtract(ctx.getDecimal(source));
            result = fitPacked(result, targetDigits, scale);
            ctx.setDecimal(target, result);
            setDecimalCondition(result, cc);
        }

        public static void mp(
                ExecutionContext ctx,
                String target,
                String source,
                int targetDigits,
                int scale,
                ConditionCode cc) {

            BigDecimal result = ctx.getDecimal(target).multiply(ctx.getDecimal(source));
            result = fitPacked(result, targetDigits, scale);
            ctx.setDecimal(target, result);
            setDecimalCondition(result, cc);
        }

        public static void dp(
                ExecutionContext ctx,
                String target,
                String source,
                int targetDigits,
                int scale,
                ConditionCode cc) {

            BigDecimal divisor = ctx.getDecimal(source);

            if (BigDecimal.ZERO.compareTo(divisor) == 0) {
                throw new ArithmeticException("Packed decimal divide by zero");
            }

            BigDecimal result = ctx.getDecimal(target).divide(divisor, scale, RoundingMode.HALF_UP);
            result = fitPacked(result, targetDigits, scale);
            ctx.setDecimal(target, result);
            setDecimalCondition(result, cc);
        }

        public static int cp(ExecutionContext ctx, String left, String right, ConditionCode cc) {
            int result = ctx.getDecimal(left).compareTo(ctx.getDecimal(right));
            setCompareCondition(result, cc);
            return result;
        }

        public static void pack(
                ExecutionContext ctx,
                String target,
                String source,
                int targetLength,
                int sourceLength,
                int targetDigits,
                int scale,
                ConditionCode cc) {

            String zoned = Memory.normalize(ctx.getString(source), sourceLength).trim();
            if (zoned.isEmpty()) {
                zoned = "0";
            }

            String cleaned = zoned.replaceAll("[^0-9+.-]", "");
            if (cleaned.isEmpty() || cleaned.equals("+") || cleaned.equals("-")) {
                cleaned = "0";
            }

            BigDecimal value = new BigDecimal(cleaned);
            BigDecimal normalized = fitPacked(value, targetDigits, scale);
            ctx.setDecimal(target, normalized);
            setDecimalCondition(normalized, cc);
        }

        public static void unpk(
                ExecutionContext ctx,
                String target,
                String source,
                int targetLength,
                int sourceLength,
                int sourceDigits,
                int scale) {

            BigDecimal value = ctx.getDecimal(source);
            String plain = value.setScale(scale, RoundingMode.HALF_UP).movePointRight(scale).abs().toPlainString();
            String zoned = Memory.normalize(plain, targetLength);
            ctx.setString(target, zoned);
        }

        public static void srp(
                ExecutionContext ctx,
                String target,
                int shiftRightDigits,
                int roundingDigit,
                int targetDigits,
                int scale,
                ConditionCode cc) {

            BigDecimal divisor = BigDecimal.TEN.pow(Math.max(0, shiftRightDigits));
            BigDecimal value = ctx.getDecimal(target).divide(divisor, scale, RoundingMode.HALF_UP);
            BigDecimal normalized = fitPacked(value, targetDigits, scale);
            ctx.setDecimal(target, normalized);
            setDecimalCondition(normalized, cc);
        }

        public static BigDecimal fitPacked(BigDecimal value, int totalDigits, int scale) {
            BigDecimal scaled = value.setScale(scale, RoundingMode.HALF_UP);
            BigDecimal absolute = scaled.abs();

            String digitsOnly = absolute
                    .movePointRight(scale)
                    .toPlainString()
                    .replace(".", "");

            if (digitsOnly.length() > totalDigits) {
                throw new ArithmeticException(
                        "Packed decimal overflow: value=" + value + " totalDigits=" + totalDigits);
            }

            return scaled;
        }

        private static void setDecimalCondition(BigDecimal value, ConditionCode cc) {
            int result = value.compareTo(BigDecimal.ZERO);

            if (result == 0) {
                cc.setEqual();
            } else if (result < 0) {
                cc.setLow();
            } else {
                cc.setHigh();
            }
        }

        public static void oi(ExecutionContext ctx, String targetOperand, int immediate, ConditionCode cc) {
            applyImmediateLogical(ctx, targetOperand, immediate, "OR", cc);
        }

        public static void xi(ExecutionContext ctx, String targetOperand, int immediate, ConditionCode cc) {
            applyImmediateLogical(ctx, targetOperand, immediate, "XOR", cc);
        }

        public static void ni(ExecutionContext ctx, String targetOperand, int immediate, ConditionCode cc) {
            applyImmediateLogical(ctx, targetOperand, immediate, "AND", cc);
        }

        private static void applyImmediateLogical(
                ExecutionContext ctx,
                String targetOperand,
                int immediate,
                String operation,
                ConditionCode cc) {

            String field = targetOperand;
            int offset = 0;

            int plus = targetOperand.indexOf('+');
            if (plus >= 0) {
                field = targetOperand.substring(0, plus);
                try {
                    offset = Integer.parseInt(targetOperand.substring(plus + 1));
                } catch (NumberFormatException ex) {
                    offset = 0;
                }
            }

            String value = ctx.getString(field);
            if (value == null) {
                value = "";
            }
            if (value.length() <= offset) {
                value = Memory.normalize(value, offset + 1);
            }

            char[] chars = value.toCharArray();
            int current = chars[offset] & 0xFF;
            int result;

            if ("AND".equals(operation)) {
                result = current & immediate;
            } else if ("XOR".equals(operation)) {
                result = current ^ immediate;
            } else {
                result = current | immediate;
            }

            chars[offset] = (char) (result & 0xFF);
            ctx.setString(field, new String(chars));

            if ((result & 0xFF) == 0) {
                cc.setEqual();
            } else {
                cc.setLow();
            }
        }

        private static void setCompareCondition(int result, ConditionCode cc) {
            if (result == 0) {
                cc.setEqual();
            } else if (result < 0) {
                cc.setLow();
            } else {
                cc.setHigh();
            }
        }
    }

    public static class Register {

        public static void xr(Registers registers, int r1, int r2, ConditionCode cc) {
            int result = registers.get(r1) ^ registers.get(r2);
            registers.set(r1, result);
            setBinaryCondition(result, cc);
        }

        public static void sr(Registers registers, int r1, int r2, ConditionCode cc) {
            int result = registers.get(r1) - registers.get(r2);
            registers.set(r1, result);
            setBinaryCondition(result, cc);
        }

        public static void ar(Registers registers, int r1, int r2, ConditionCode cc) {
            int result = registers.get(r1) + registers.get(r2);
            registers.set(r1, result);
            setBinaryCondition(result, cc);
        }

        public static void ltr(Registers registers, int r1, int r2, ConditionCode cc) {
            int value = registers.get(r2);
            registers.set(r1, value);
            setBinaryCondition(value, cc);
        }

        public static void lr(Registers registers, int r1, int r2) {
            registers.set(r1, registers.get(r2));
        }

        public static void lh(Registers registers, int register, short halfword) {
            registers.set(register, halfword);
        }

        public static void l(Registers registers, int register, int fullword) {
            registers.set(register, fullword);
        }

        public static void loadFullword(ExecutionContext ctx, Registers registers, int register, String field) {
            registers.set(register, ctx.getInt(field));
        }

        public static void storeFullword(ExecutionContext ctx, Registers registers, int register, String field) {
            ctx.setInt(field, registers.get(register));
        }

        public static void storeStringFromRegister(ExecutionContext ctx, Registers registers, int register, String field) {
            ctx.setString(field, String.valueOf(registers.get(register)));
        }

        public static void aImmediate(Registers registers, int register, int value, ConditionCode cc) {
            int result = registers.get(register) + value;
            registers.set(register, result);
            setBinaryCondition(result, cc);
        }

        public static void cImmediate(Registers registers, int register, int value, ConditionCode cc) {
            int result = Integer.compare(registers.get(register), value);
            if (result == 0) {
                cc.setEqual();
            } else if (result < 0) {
                cc.setLow();
            } else {
                cc.setHigh();
            }
        }

        public static void a(ExecutionContext ctx, Registers registers, int register, String field, ConditionCode cc) {
            int result = registers.get(register) + ctx.getInt(field);
            registers.set(register, result);
            setBinaryCondition(result, cc);
        }

        public static void c(ExecutionContext ctx, Registers registers, int register, String field, ConditionCode cc) {
            int result = Integer.compare(registers.get(register), ctx.getInt(field));
            if (result == 0) {
                cc.setEqual();
            } else if (result < 0) {
                cc.setLow();
            } else {
                cc.setHigh();
            }
        }

        public static void cr(Registers registers, int r1, int r2, ConditionCode cc) {
            int result = Integer.compare(registers.get(r1), registers.get(r2));
            if (result == 0) {
                cc.setEqual();
            } else if (result < 0) {
                cc.setLow();
            } else {
                cc.setHigh();
            }
        }

        private static void setBinaryCondition(int value, ConditionCode cc) {
            if (value == 0) {
                cc.setEqual();
            } else if (value < 0) {
                cc.setLow();
            } else {
                cc.setHigh();
            }
        }
    }

    public static class Address {
        private final String field;
        private final Integer immediate;

        private Address(String field, Integer immediate) {
            this.field = field;
            this.immediate = immediate;
        }

        public static Address ofField(String field) {
            return new Address(field, null);
        }

        public static Address ofImmediate(int value) {
            return new Address(null, value);
        }

        public static Address ofBaseOffset(Registers registers, int baseRegister, int offset) {
            return new Address(null, registers.get(baseRegister) + offset);
        }

        public static Address ofIndexed(Registers registers, int baseRegister, int indexRegister, int offset) {
            return new Address(null, registers.get(baseRegister) + registers.get(indexRegister) + offset);
        }

        public static void la(ExecutionContext ctx, Registers registers, int register, Address address) {
            if (address.immediate != null) {
                registers.set(register, address.immediate);
            } else if (address.field != null) {
                registers.set(register, Math.abs(address.field.hashCode()));
            } else {
                registers.set(register, 0);
            }
        }
    }

    public static class IO {
        /*
         * Local DDNAME adapter for validation.
         *
         * The generated translator emits generic mainframe-style calls:
         *   OPEN / GET / PUT / CLOSE
         *
         * This adapter maps those calls to local fixed-width files.  It also
         * records the last I/O return code in __LAST_IO_RC so translated code
         * can move that value into R15 and use normal LTR/JZ/BNZ branch flow.
         */

        public static void open(ExecutionContext ctx, ConditionCode cc, String... resources) {
            ctx.set("IO_OPEN", String.join(",", resources));
            ctx.setInt("__LAST_IO_RC", 0);
            cc.setEqual();
        }

        public static void close(ExecutionContext ctx, ConditionCode cc, String... resources) {
            ctx.set("IO_CLOSE", String.join(",", resources));
            ctx.setInt("__LAST_IO_RC", 0);
            cc.setEqual();
        }

        public static void get(ExecutionContext ctx, String resource, String recordField, ConditionCode cc) {
            String effectiveRecordField = effectiveInputRecordField(ctx, resource, recordField);
            String force = ctx.getString("IO_FORCE_READ");

            // Behavior-comparator context mode: data is already staged in ctx.
            if (!"true".equalsIgnoreCase(force) && contextAlreadyHasTransaction(ctx)) {
                ctx.setInt("__LAST_IO_RC", 0);
                cc.setEqual();
                return;
            }

            String staged = ctx.getString(resource + "_NEXT");
            if (staged != null && !staged.isEmpty()) {
                storeRecord(ctx, effectiveRecordField, staged);
                ctx.setInt("__LAST_IO_RC", 0);
                cc.setEqual();
                return;
            }

            String path = resolveInputPath(ctx, resource, effectiveRecordField);

            if (path == null || path.isEmpty()) {
                ctx.setInt("__LAST_IO_RC", 8);
                cc.setHigh();
                return;
            }

            try {
                java.nio.file.Path filePath = existingPath(path);

                if (filePath == null || !java.nio.file.Files.exists(filePath)) {
                    ctx.setString("IO_ERROR", "Input file not found: " + path);
                    ctx.setInt("__LAST_IO_RC", 8);
                    cc.setHigh();
                    return;
                }

                java.util.List<String> lines = java.nio.file.Files.readAllLines(
                        filePath,
                        java.nio.charset.StandardCharsets.UTF_8);

                String cursorKey = "IO_CURSOR_" + sanitizeKey(resource) + "_" + sanitizeKey(effectiveRecordField);
                int pos = ctx.getInt(cursorKey);

                if (pos >= lines.size()) {
                    ctx.setInt("__LAST_IO_RC", 4);
                    cc.setHigh();
                    return;
                }

                String record = lines.get(pos);
                ctx.setInt(cursorKey, pos + 1);
                storeRecord(ctx, effectiveRecordField, record);
                ctx.setInt("__LAST_IO_RC", 0);
                cc.setEqual();

            } catch (Exception ex) {
                ctx.setString("IO_ERROR", ex.getMessage() == null ? ex.toString() : ex.getMessage());
                ctx.setInt("__LAST_IO_RC", 8);
                cc.setHigh();
            }
        }

        public static void put(ExecutionContext ctx, String resource, String recordField, ConditionCode cc) {
            String effectiveRecordField = effectiveOutputRecordField(ctx, resource, recordField);
            String record = ctx.getString(effectiveRecordField);

            if (record == null || record.isEmpty()) {
                record = ctx.getString("IN_RECORD");
            }
            if (record == null) {
                record = "";
            }

            ctx.setString(resource + "_LAST_WRITE", record);

            String path = resolveOutputPath(ctx, resource, effectiveRecordField);

            if (path == null || path.isEmpty()) {
                ctx.setInt("__LAST_IO_RC", 0);
                cc.setEqual();
                return;
            }

            try {
                java.nio.file.Path filePath = outputPath(path);
                java.nio.file.Path parent = filePath.getParent();

                if (parent != null) {
                    java.nio.file.Files.createDirectories(parent);
                }

                java.nio.file.Files.write(
                        filePath,
                        java.util.Arrays.asList(record),
                        java.nio.charset.StandardCharsets.UTF_8,
                        java.nio.file.StandardOpenOption.CREATE,
                        java.nio.file.StandardOpenOption.APPEND);

                ctx.setInt("__LAST_IO_RC", 0);
                cc.setEqual();

            } catch (Exception ex) {
                ctx.setString("IO_ERROR", ex.getMessage() == null ? ex.toString() : ex.getMessage());
                ctx.setInt("__LAST_IO_RC", 8);
                cc.setHigh();
            }
        }

        private static String effectiveInputRecordField(ExecutionContext ctx, String resource, String recordField) {
            if (recordField != null && !recordField.isEmpty()) {
                return recordField;
            }

            String explicit = ctx.getString("IO_RECORD_FIELD");
            if (!explicit.isEmpty()) {
                return explicit;
            }

            String text = resource == null ? "" : resource.toUpperCase();

            if (!ctx.getString("VSAMIN_PATH").isEmpty()) {
                return "IN_RECORD";
            }

            if (text.contains("RPL") || text.contains("CURRTX") || !ctx.getString("CURRTX_PATH").isEmpty()) {
                return "CURRTX";
            }

            if (!ctx.getString("IN_RECORD_PATH").isEmpty()) {
                return "IN_RECORD";
            }

            return "IN_RECORD";
        }

        private static String effectiveOutputRecordField(ExecutionContext ctx, String resource, String recordField) {
            if (recordField != null && !recordField.isEmpty()) {
                return recordField;
            }

            String explicit = ctx.getString("IO_OUTPUT_RECORD_FIELD");
            if (!explicit.isEmpty()) {
                return explicit;
            }

            if (!ctx.getString("OUT_RECORD").isEmpty()) {
                return "OUT_RECORD";
            }

            if (!ctx.getString("IN_RECORD").isEmpty()) {
                return "IN_RECORD";
            }

            if (!ctx.getString("CURRTX").isEmpty()) {
                return "CURRTX";
            }

            return "OUT_RECORD";
        }

        private static boolean contextAlreadyHasTransaction(ExecutionContext ctx) {
            return !ctx.getString("TXCUST").isEmpty()
                    || !ctx.getString("TXAMT").isEmpty()
                    || !ctx.getString("TXLIMIT").isEmpty()
                    || !ctx.getString("TXSTAT").isEmpty()
                    || !ctx.getString("TXTYPE").isEmpty();
        }

        private static void storeRecord(ExecutionContext ctx, String recordField, String record) {
            if (recordField != null && !recordField.isEmpty()) {
                ctx.setString(recordField, record);
            }

            if ("CURRTX".equalsIgnoreCase(recordField)) {
                parseCurrentTransactionRecord(ctx, record);
            }

            if ("IN_RECORD".equalsIgnoreCase(recordField) && ctx.getString("OUT_RECORD").isEmpty()) {
                ctx.setString("OUT_RECORD", record);
            }
        }

        private static void parseCurrentTransactionRecord(ExecutionContext ctx, String record) {
            /*
             * Local TXREAD fixed-width validation layout:
             * TXCARD   0-15   16 chars
             * TXCUST   16-25  10 chars
             * TXAMT    26-33   8 chars, cents
             * TXTYPE   34-35   2 chars
             * TXSTAT   36-36   1 char
             * TXLIMIT  37-44   8 chars, cents
             * TXFEE    45-52   8 chars, cents
             */
            String value = Memory.normalize(record, 53);

            ctx.setString("TXCARD", value.substring(0, 16).trim());
            ctx.setString("TXCUST", value.substring(16, 26).trim());
            setMoneyFromCents(ctx, "TXAMT", value.substring(26, 34));
            ctx.setString("TXTYPE", value.substring(34, 36).trim());
            ctx.setString("TXSTAT", value.substring(36, 37).trim());
            setMoneyFromCents(ctx, "TXLIMIT", value.substring(37, 45));
            setMoneyFromCents(ctx, "TXFEE", value.substring(45, 53));
        }

        private static void setMoneyFromCents(ExecutionContext ctx, String field, String centsText) {
            String cleaned = centsText == null ? "" : centsText.replaceAll("[^0-9+-]", "");

            if (cleaned.isEmpty() || "+".equals(cleaned) || "-".equals(cleaned)) {
                cleaned = "0";
            }

            java.math.BigDecimal value = new java.math.BigDecimal(cleaned)
                    .movePointLeft(2)
                    .setScale(2, java.math.RoundingMode.HALF_UP);

            ctx.setDecimal(field, value);
        }

        private static String resolveInputPath(ExecutionContext ctx, String resource, String recordField) {
            String safeResource = resource == null ? "" : resource;
            String safeRecordField = recordField == null ? "" : recordField;

            String resourcePath = ctx.getString(safeResource + "_PATH");
            if (!resourcePath.isEmpty()) {
                return resourcePath;
            }

            String fieldPath = ctx.getString(safeRecordField + "_PATH");
            if (!fieldPath.isEmpty()) {
                return fieldPath;
            }

            String resourceDdname = ctx.getString(safeResource + "_DDNAME");
            if (!resourceDdname.isEmpty()) {
                return "test_cases/ps/" + resourceDdname.toUpperCase() + ".txt";
            }

            String fieldDdname = ctx.getString(safeRecordField + "_DDNAME");
            if (!fieldDdname.isEmpty()) {
                return "test_cases/ps/" + fieldDdname.toUpperCase() + ".txt";
            }

            if ("CURRTX".equalsIgnoreCase(safeRecordField)) {
                return "test_cases/ps/INVSAM.txt";
            }

            if ("IN_RECORD".equalsIgnoreCase(safeRecordField)) {
                return "test_cases/ps/VSAMIN.txt";
            }

            if ("INRPL".equalsIgnoreCase(safeResource) || "INACB".equalsIgnoreCase(safeResource)) {
                return "test_cases/ps/INVSAM.txt";
            }

            if (safeResource.matches("[A-Za-z0-9_#$@]+")) {
                return "test_cases/ps/" + safeResource.toUpperCase() + ".txt";
            }

            return "";
        }


        private static String resolveOutputPath(ExecutionContext ctx, String resource, String recordField) {
            String safeResource = resource == null ? "" : resource;
            String safeRecordField = recordField == null ? "" : recordField;

            String resourcePath = ctx.getString(safeResource + "_PATH");
            if (!resourcePath.isEmpty()) {
                return resourcePath;
            }

            String fieldPath = ctx.getString(safeRecordField + "_PATH");
            if (!fieldPath.isEmpty()) {
                return fieldPath;
            }

            String resourceDdname = ctx.getString(safeResource + "_DDNAME");
            if (!resourceDdname.isEmpty()) {
                return "test_cases/ps/" + resourceDdname.toUpperCase() + ".txt";
            }

            String fieldDdname = ctx.getString(safeRecordField + "_DDNAME");
            if (!fieldDdname.isEmpty()) {
                return "test_cases/ps/" + fieldDdname.toUpperCase() + ".txt";
            }

            if ("LOGBUFF".equalsIgnoreCase(safeRecordField)
                    || "OUTRPL".equalsIgnoreCase(safeResource)
                    || "OUTACB".equalsIgnoreCase(safeResource)) {
                return "test_cases/ps/OUTVSAM.txt";
            }

            if ("OUT_RECORD".equalsIgnoreCase(safeRecordField)
                    || "OUTFILE".equalsIgnoreCase(safeResource)) {
                return "test_cases/ps/VSAMOUT.txt";
            }

            if (safeResource.matches("[A-Za-z0-9_#$@]+")) {
                return "test_cases/ps/" + safeResource.toUpperCase() + ".txt";
            }

            return "";
        }


        private static String sanitizeKey(String value) {
            if (value == null || value.isEmpty()) {
                return "RESOURCE";
            }
            return value.replaceAll("[^A-Za-z0-9_#$@]", "_");
        }

        private static java.nio.file.Path existingPath(String path) {
            java.nio.file.Path direct = java.nio.file.Paths.get(path);

            if (java.nio.file.Files.exists(direct)) {
                return direct;
            }

            java.nio.file.Path parentRelative = java.nio.file.Paths.get("..", path);

            if (java.nio.file.Files.exists(parentRelative)) {
                return parentRelative;
            }

            return direct;
        }

        private static java.nio.file.Path outputPath(String path) {
            java.nio.file.Path direct = java.nio.file.Paths.get(path);
            java.nio.file.Path parent = direct.getParent();

            if (parent != null && java.nio.file.Files.exists(parent)) {
                return direct;
            }

            return java.nio.file.Paths.get("..", path);
        }
    }

    public static class Program {
        public static void save(Registers registers) {
            // Generated runtime placeholder for SAVE macro.
        }
    }

    public static class Branch {

        public static final int MAX_LOOP_ITERATIONS = 100000;

        public static boolean isEqual(ConditionCode cc) {
            return cc.get() == ConditionCode.EQUAL;
        }

        public static boolean isNotEqual(ConditionCode cc) {
            return cc.get() != ConditionCode.EQUAL;
        }

        public static boolean isLow(ConditionCode cc) {
            return cc.get() == ConditionCode.LOW;
        }

        public static boolean isHigh(ConditionCode cc) {
            return cc.get() == ConditionCode.HIGH;
        }

        public static boolean bct(Registers registers, int register) {
            registers.decrement(register);
            return registers.get(register) != 0;
        }

        public static boolean bctr(Registers registers, int register) {
            registers.decrement(register);
            return registers.get(register) != 0;
        }

        public static boolean isNotHigh(ConditionCode cc) {
            return cc.get() != ConditionCode.HIGH;
       }

        public static boolean isNotLow(ConditionCode cc) {
            return cc.get() != ConditionCode.LOW;
        }

        public static boolean isOverflow(ConditionCode cc) {
            return cc.get() == ConditionCode.OVERFLOW;
        }

        public static boolean isNotOverflow(ConditionCode cc) {
            return cc.get() != ConditionCode.OVERFLOW;
        }
    }
}
