/*
 * Generated by Legacy Assembler Modernization Intelligence Platform.
 * Artifact: AssemblerModule
 */

public interface AssemblerModule {

    String name();

    ModuleResult execute(ExecutionContext ctx);
}
