/*
 * Generated by Legacy Assembler Modernization Intelligence Platform.
 *
 * Generated artifact: AssemblerModule
 *
 * This is an application-independent Java replacement candidate.
 * Review analyzer notes before production use.
 */

public interface AssemblerModule {

    String name();

    ModuleResult execute(ExecutionContext ctx);
}
