/*
 * Generated by Legacy Assembler Modernization Intelligence Platform.
 * Artifact: Bctcount
 */

public class Bctcount implements AssemblerModule {

    private final AsmRuntime.ConditionCode cc = new AsmRuntime.ConditionCode();
    private final AsmRuntime.Registers registers = new AsmRuntime.Registers();

    @Override
    public String name() {
        return "BCTCOUNT";
    }

    @Override
    public ModuleResult execute(ExecutionContext ctx) {

        /*
         * HLASM Module: BCTCOUNT
         *
         * Business fields read:
         *   - COUNT
         * Business fields written:
         *   - TOTAL
         */


        // Generic BCT accumulator loop reconstructed from BCT back-edge pattern.
        int __counter = ctx.getInt("COUNT");
        int __total = 0;

        while (__counter > 0) {
            __total += __counter;
            __counter--;
        }

        ctx.setInt("TOTAL", __total);
        registers.clear(15);
        return ModuleResult.rc(0, "BCTCOUNT BCT loop completed");




    }
}
