/*
 * Generated by Legacy Assembler Modernization Intelligence Platform.
 * Artifact: Bctcount
 */

public class Bctcount implements AssemblerModule {

    private final AsmRuntime.ConditionCode cc = new AsmRuntime.ConditionCode();
    private final AsmRuntime.Registers registers = new AsmRuntime.Registers();

    @Override
    public String name() {
        return "BCTCOUNT";
    }

    @Override
    public ModuleResult execute(ExecutionContext ctx) {

        /*
         * HLASM Module: BCTCOUNT
         *
         * Business fields read:
         *   - COUNT
         * Business fields written:
         *   - TOTAL
         */

        // Branch-aware translated instruction candidates from HLASM source.
        // LABEL: BCTCOUNT
        // CSECT directive: BCTCOUNT  CSECT
        // subroutine call via BASR: BASR  R12,0              Establish base register
        // USING directive: USING *,R12              Establish addressability
        registers.clear(3);
        registers.set(4, ctx.getInt("COUNT"));
        // LABEL: LOOPSTART
        // Backward BCT loop lowered from CFG target LOOPSTART to BCT at source index 7.
        int __bctLoopGuard0 = 0;
        do {
            AsmRuntime.Register.ar(registers, 3, 4, cc);
            if (++__bctLoopGuard0 > AsmRuntime.Branch.MAX_LOOP_ITERATIONS) {
                throw new IllegalStateException("BCT loop exceeded safety limit; possible infinite assembler loop");
            }
        } while (AsmRuntime.Branch.bct(registers, 4));
        ctx.setInt("TOTAL", registers.get(3));
        registers.clear(15);
        return ModuleResult.rc(registers.get(15), "Returned by translated BR");



    }
}
