/*
 * Generated by Legacy Assembler Modernization Intelligence Platform.
 * Artifact: Cardstat
 */

public class Cardstat implements AssemblerModule {

    private final AsmRuntime.ConditionCode cc = new AsmRuntime.ConditionCode();
    private final AsmRuntime.Registers registers = new AsmRuntime.Registers();

    @Override
    public String name() {
        return "CARDSTAT";
    }

    @Override
    public ModuleResult execute(ExecutionContext ctx) {

        /*
         * HLASM Module: CARDSTAT
         *
         * Business fields read:
         *   - TXSTAT
         * Business fields written:
         *   - ERRCODE
         * Conditions:
         *   - CLI TXSTAT, C'A'
         */

        // Branch-aware translated instruction candidates from HLASM source.
        // LABEL: CARDSTAT
        // CSECT directive: CARDSTAT CSECT ,                   Administrative Block Reviewer
        // TODO protected semantic translation for BAKR: Branch-and-stack requires linkage-stack/runtime support.
        //      category=control_flow_linkage; proposed_helper=AsmRuntime.Branch.bakr; source: BAKR  14,0                Save registers on linkage stack
        // subroutine call via BASR: BASR  12,0
        // USING directive: USING *,12
        // TODO LM already handled by analyzer register_map when possible: LM    2,3,0(1)            R2 = Addr of CURRTX, R3 = Addr of ERRCODE
        AsmRuntime.Memory.cli(ctx, "TXSTAT", 'A', cc);
        if (AsmRuntime.Branch.isNotEqual(cc)) {
            AsmRuntime.Memory.mvcLiteral(ctx, "ERRCODE", 4, "E002");
            return ModuleResult.rc(4, "Rejected by translated branch logic");
        }
        // LABEL: STAT_OK
        // DS declaration: STAT_OK  DS    0H
        registers.clear(15);
        return ModuleResult.rc(registers.get(15), "Returned by translated PR");



    }
}
