/*
 * Generated by Legacy Assembler Modernization Intelligence Platform.
 * Artifact: ExecutionContext
 */

import java.math.BigDecimal;
import java.util.HashMap;
import java.util.Map;

public class ExecutionContext {

    private final Map<String, Object> fields = new HashMap<>();

    public Object get(String fieldName) {
        return fields.get(fieldName);
    }

    public void set(String fieldName, Object value) {
        fields.put(fieldName, value);
    }

    public String getString(String fieldName) {
        Object value = fields.get(fieldName);
        return value == null ? "" : value.toString();
    }

    public void setString(String fieldName, String value) {
        fields.put(fieldName, value);
    }

    public BigDecimal getDecimal(String fieldName) {
        Object value = fields.get(fieldName);

        if (value == null) {
            return BigDecimal.ZERO;
        }

        if (value instanceof BigDecimal) {
            return (BigDecimal) value;
        }

        return new BigDecimal(value.toString());
    }

    public void setDecimal(String fieldName, BigDecimal value) {
        fields.put(fieldName, value);
    }

    public int getInt(String fieldName) {
        Object value = fields.get(fieldName);

        if (value == null) {
            return 0;
        }

        if (value instanceof Number) {
            return ((Number) value).intValue();
        }

        return Integer.parseInt(value.toString().trim());
    }

    public void setInt(String fieldName, int value) {
        fields.put(fieldName, value);
    }

    public Map<String, Object> snapshot() {
        return new HashMap<>(fields);
    }
}
