/*
 * Generated by Legacy Assembler Modernization Intelligence Platform.
 * Artifact: Frdchk
 */

public class Frdchk implements AssemblerModule {

    private final AsmRuntime.ConditionCode cc = new AsmRuntime.ConditionCode();
    private final AsmRuntime.Registers registers = new AsmRuntime.Registers();

    @Override
    public String name() {
        return "FRDCHK";
    }

    @Override
    public ModuleResult execute(ExecutionContext ctx) {

        /*
         * HLASM Module: FRDCHK
         *
         * Business fields read:
         *   - TXAMT
         *   - TXTYPE
         * Business fields written:
         *   - ERRCODE
         * Conditions:
         *   - CP TXAMT, =P'50000'
         *   - CLC TXTYPE, =C'RE'
         */

        // Branch-aware translated instruction candidates from HLASM source.
        // LABEL: FRDCHK
        // CSECT directive: FRDCHK   CSECT ,                   Fraud Risk Analytical Engine
        // TODO manual review required: BAKR  14,0                Save execution context
        // subroutine call via BASR: BASR  12,0
        // USING directive: USING ,12
        // TODO LM already handled by analyzer register_map when possible: LM    2,3,0(1)            R2 = Addr of CURRTX, R3 = Addr of ERRCODE
        ctx.setDecimal("TXAMT_LITERAL_COMPARE", new java.math.BigDecimal("50000"));
        AsmRuntime.Packed.cp(ctx, "TXAMT", "TXAMT_LITERAL_COMPARE", cc);
        if (AsmRuntime.Branch.isHigh(cc)) {
            AsmRuntime.Memory.clcLiteral(ctx, "TXTYPE", 2, "RE", cc);
            if (AsmRuntime.Branch.isNotEqual(cc)) {
                // branch to FRD_OK
            }
            AsmRuntime.Memory.mvcLiteral(ctx, "ERRCODE", 4, "E004");
            return ModuleResult.rc(4, "Rejected by translated branch logic");
        }
        // LABEL: FRD_OK
        // DS declaration: FRD_OK   DS    0H
        registers.clear(15);
        // TODO manual review required: PR
        // TODO manual review required: LTORG ,
        // TODO manual review required: END   FRDCHK

        return ModuleResult.rc(0, "FRDCHK executed as generated candidate");
    }
}
