/*
 * Generated by Legacy Assembler Modernization Intelligence Platform.
 * Artifact: Maindrv
 */

public class Maindrv implements AssemblerModule {

    private final AsmRuntime.ConditionCode cc = new AsmRuntime.ConditionCode();
    private final AsmRuntime.Registers registers = new AsmRuntime.Registers();

    @Override
    public String name() {
        return "MAINDRV";
    }

    @Override
    public ModuleResult execute(ExecutionContext ctx) {

        /*
         * HLASM Module: MAINDRV
         *
         * Conditions:
         *   - LTR 15, 15
         *   - LTR 15, 15
         *   - C 15, =F'4'
         *   - LTR 15, 15
         *   - LTR 15, 15
         *   - LTR 15, 15
         *   - LTR 15, 15
         */

        // Application orchestration discovered from HLASM module call references.
        // Driver module: MAINDRV
        ModuleResult result = ModuleResult.rc(0, "Application orchestration started");

        // Call discovered module: TXREAD
        result = new Txread().execute(ctx);

        // Call discovered module: CUSTVAL
        result = new Custval().execute(ctx);
        if (result.getReturnCode() != 0) {
            return result;
        }

        // Call discovered module: CARDSTAT
        result = new Cardstat().execute(ctx);
        if (result.getReturnCode() != 0) {
            return result;
        }

        // Call discovered module: LIMITCHK
        result = new Limitchk().execute(ctx);
        if (result.getReturnCode() != 0) {
            return result;
        }

        // Call discovered module: FRDCHK
        result = new Frdchk().execute(ctx);
        if (result.getReturnCode() != 0) {
            return result;
        }

        // Call discovered module: FEECALC
        result = new Feecalc().execute(ctx);

        // Call discovered module: AUTHDEC
        result = new Authdec().execute(ctx);

        // Call discovered module: AUDWRITE
        result = new Audwrite().execute(ctx);

        return ModuleResult.rc(result.getReturnCode(), "Application orchestration completed");



    }
}
