/*
 * Generated by Legacy Assembler Modernization Intelligence Platform.
 * Artifact: ModernizationRuntime
 */

import java.util.ArrayList;
import java.util.List;

public class ModernizationRuntime {

    private final List<AssemblerModule> modules = new ArrayList<>();

    public ModernizationRuntime() {
        modules.add(new Audwrite());
        modules.add(new Authdec());
        modules.add(new Cardstat());
        modules.add(new Custval());
        modules.add(new Feecalc());
        modules.add(new Frdchk());
        modules.add(new Limitchk());
        modules.add(new Maindrv());
        modules.add(new Txread());
    }

    public List<ModuleResult> execute(ExecutionContext ctx) {
        List<ModuleResult> results = new ArrayList<>();

        for (AssemblerModule module : modules) {
            ModuleResult result = module.execute(ctx);
            results.add(result);

            if (!result.isOk()) {
                break;
            }
        }

        return results;
    }
}
