/*
 * Generated by Legacy Assembler Modernization Intelligence Platform.
 *
 * Generated artifact: ModuleResult
 *
 * This is an application-independent Java replacement candidate.
 * Review analyzer notes before production use.
 */

public class ModuleResult {

    private final int returnCode;
    private final String message;

    public ModuleResult(int returnCode, String message) {
        this.returnCode = returnCode;
        this.message = message;
    }

    public int getReturnCode() {
        return returnCode;
    }

    public String getMessage() {
        return message;
    }

    public boolean isOk() {
        return returnCode == 0;
    }

    public static ModuleResult ok() {
        return new ModuleResult(0, "OK");
    }

    public static ModuleResult rc(int rc, String message) {
        return new ModuleResult(rc, message);
    }
}
