/*
 * Generated by Legacy Assembler Modernization Intelligence Platform.
 * Artifact: Txread
 */

public class Txread implements AssemblerModule {

    private final AsmRuntime.ConditionCode cc = new AsmRuntime.ConditionCode();
    private final AsmRuntime.Registers registers = new AsmRuntime.Registers();

    @Override
    public String name() {
        return "TXREAD";
    }

    @Override
    public ModuleResult execute(ExecutionContext ctx) {

        /*
         * HLASM Module: TXREAD
         *
         * Business fields read:
         *   - INRPL
         * Business fields written:
         *   - CURRTX
         * Conditions:
         *   - LTR 15, 15
         */

        // Generic GET adapter generated from HLASM GET + analyzer metadata.
        String __recordField = "CURRTX";
        String __path = "";

        for (String __key : new String[] {"INRPL_PATH", "CURRTX_PATH", "INACB_PATH", "INVSAM_PATH", "OUTACB_PATH", "OUTVSAM_PATH", "VSAMIN_PATH", "OUTFILE_PATH", "VSAMOUT_PATH"}) {
            String __candidate = ctx.getString(__key);
            if (__candidate != null && !__candidate.isEmpty()) {
                __path = __candidate;
                break;
            }
        }

        if (__path.isEmpty()) {
            for (String __candidate : new String[] {"test_cases/ps/INVSAM.txt", "../test_cases/ps/INVSAM.txt", "test_cases/ps/OUTVSAM.txt", "../test_cases/ps/OUTVSAM.txt", "test_cases/ps/VSAMIN.txt", "../test_cases/ps/VSAMIN.txt", "test_cases/ps/VSAMOUT.txt", "../test_cases/ps/VSAMOUT.txt", "test_cases/ps/INRPL.txt", "../test_cases/ps/INRPL.txt"}) {
                java.nio.file.Path __candidatePath = java.nio.file.Paths.get(__candidate);
                if (java.nio.file.Files.exists(__candidatePath)) {
                    __path = __candidate;
                    break;
                }
            }
        }

        if (__path.isEmpty()) {
            ctx.setString("IO_ERROR", "Input file not found for GET module " + name());
            registers.set(15, 8);
            ctx.setInt("__LAST_IO_RC", 8);
            return ModuleResult.rc(8, "TXREAD GET failed: no input path");
        }

        try {
            java.nio.file.Path __file = java.nio.file.Paths.get(__path);
            if (!java.nio.file.Files.exists(__file)) {
                java.nio.file.Path __alt = java.nio.file.Paths.get("..", __path);
                if (java.nio.file.Files.exists(__alt)) {
                    __file = __alt;
                }
            }

            if (!java.nio.file.Files.exists(__file)) {
                ctx.setString("IO_ERROR", "Input file not found: " + __path);
                registers.set(15, 8);
                ctx.setInt("__LAST_IO_RC", 8);
                return ModuleResult.rc(8, "TXREAD GET failed: file missing");
            }

            java.util.List<String> __lines = java.nio.file.Files.readAllLines(
                    __file,
                    java.nio.charset.StandardCharsets.UTF_8);

            if (__lines.isEmpty()) {
                registers.set(15, 4);
                ctx.setInt("__LAST_IO_RC", 4);
                return ModuleResult.rc(4, "TXREAD GET EOF");
            }

            String __record = __lines.get(0);
            ctx.setString(__recordField, __record);
            ctx.setString("IO_ERROR", "");
            ctx.setInt("__LAST_IO_RC", 0);

            if ("CURRTX".equalsIgnoreCase(__recordField)) {
                String __value = AsmRuntime.Memory.normalize(__record, 53);
                ctx.setString("TXCARD", __value.substring(0, 16).trim());
                ctx.setString("TXCUST", __value.substring(16, 26).trim());
                ctx.setMoneyFromCents("TXAMT", __value.substring(26, 34));
                ctx.setString("TXTYPE", __value.substring(34, 36).trim());
                ctx.setString("TXSTAT", __value.substring(36, 37).trim());
                ctx.setMoneyFromCents("TXLIMIT", __value.substring(37, 45));
                ctx.setMoneyFromCents("TXFEE", __value.substring(45, 53));
            }

            registers.clear(15);
            return ModuleResult.rc(0, "TXREAD GET completed");

        } catch (Exception ex) {
            ctx.setString("IO_ERROR", ex.getMessage() == null ? ex.toString() : ex.getMessage());
            registers.set(15, 8);
            ctx.setInt("__LAST_IO_RC", 8);
            return ModuleResult.rc(8, "TXREAD GET exception");
        }



    }
}
