/*
 * Generated by Legacy Assembler Modernization Intelligence Platform.
 * Artifact: Txread
 */

public class Txread implements AssemblerModule {

    private final AsmRuntime.ConditionCode cc = new AsmRuntime.ConditionCode();
    private final AsmRuntime.Registers registers = new AsmRuntime.Registers();

    @Override
    public String name() {
        return "TXREAD";
    }

    @Override
    public ModuleResult execute(ExecutionContext ctx) {

        /*
         * HLASM Module: TXREAD
         *
         * Business fields read:
         *   - INRPL
         * Business fields written:
         *   - CURRTX
         * Conditions:
         *   - LTR 15, 15
         */

        // Branch-aware translated instruction candidates from HLASM source.
        // LABEL: TXREAD
        // CSECT directive: TXREAD   CSECT ,                   VSAM Sequential Input Processor
        // TODO manual review required: BAKR  14,0                Save registers on stack
        // subroutine call via BASR: BASR  12,0
        // USING directive: USING *,12
        // TODO LM already handled by analyzer register_map when possible: LM    2,3,0(1)            R2 = Addr of INRPL, R3 = Addr of CURRTX
        // TODO manual review required: GET   RPL=(2)             Retrieve record into CURRTX buffer
        AsmRuntime.Register.ltr(registers, 15, 15, cc);
        // TODO manual review required: JZ    GET_SUCCESS         If 0, line extracted cleanly
        // TODO L requires memory/address resolution before exact helper call: L     4,4(,2)             Access the RPL feedback control field
        // TODO manual review required: CLM   4,B'0001',=X'04'    Is the specific feedback code End of File?
        if (AsmRuntime.Branch.isNotEqual(cc)) {
            registers.set(15, 8);
        }
        // LABEL: GET_EOF
        // DS declaration: GET_EOF  DS    0H
        registers.set(15, 4);
        // TODO manual review required: PR
        // LABEL: GET_SUCCESS
        // DS declaration: GET_SUCCESS DS 0H
        registers.clear(15);
        // TODO manual review required: PR
        // TODO manual review required: LTORG ,
        // TODO manual review required: END   TXREAD

        return ModuleResult.rc(0, "TXREAD executed as generated candidate");

    }
}
