/*
 * Generated by Legacy Assembler Modernization Intelligence Platform.
 * Artifact: Vsampack
 */

public class Vsampack implements AssemblerModule {

    private final AsmRuntime.ConditionCode cc = new AsmRuntime.ConditionCode();
    private final AsmRuntime.Registers registers = new AsmRuntime.Registers();

    @Override
    public String name() {
        return "VSAMPACK";
    }

    @Override
    public ModuleResult execute(ExecutionContext ctx) {

        /*
         * HLASM Module: VSAMPACK
         *
         * Business fields read:
         *   - WS_PACKED_AMT
         *   - WS_TAX_AMT
         *   - WS_ZONED_TAX
         *   - IN_RECORD
         * Business fields written:
         *   - WS_TAX_AMT
         *   - OUT_RECORD
         * Conditions:
         *   - LTR R15, R15
         *   - CLI 0(R4), C'A'
         *   - CLI 0(R4), C'B'
         *   - CLI 0(R4), C'T'
         *   - CLI 0(R4), C'X'
         *   - LTR R5, R5
         */

        // Branch-aware translated instruction candidates from HLASM source.
        // LABEL: VSAMPACK
        // CSECT directive: VSAMPACK CSECT
        AsmRuntime.Program.save(registers);
        // subroutine call via BALR: BALR  R12,0                    Establish program base register
        // USING directive: USING *,R12
        AsmRuntime.IO.open(ctx, cc, "INVSAM", "INPUT", "OUTFILE", "OUTPUT");
        AsmRuntime.Register.ltr(registers, 15, 15, cc);
        if (AsmRuntime.Branch.isNotEqual(cc)) {
            // branch to ERR_OPEN
        }
        // LABEL: READ_REC
        // EQU declaration: READ_REC EQU   *
        AsmRuntime.IO.get(ctx, "INVSAM", "IN_RECORD", cc); registers.clear(15);
        AsmRuntime.Address.la(ctx, registers, 4, AsmRuntime.Address.ofField("IN_RECORD"));
        AsmRuntime.Address.la(ctx, registers, 6, AsmRuntime.Address.ofField("IN_RECORD"));
        AsmRuntime.Register.aImmediate(registers, 6, 100, cc);
        registers.clear(5);
        // LABEL: SCAN_LOOP
        // EQU declaration: SCAN_LOOP EQU  *
        AsmRuntime.Register.cr(registers, 4, 6, cc);
        if (AsmRuntime.Branch.isLow(cc)) {
            AsmRuntime.Memory.cli(ctx, "0(R4)", 'A', cc);
            if (AsmRuntime.Branch.isEqual(cc)) {
                // branch to SKIP_A
            }
            AsmRuntime.Memory.cli(ctx, "0(R4)", 'B', cc);
            if (AsmRuntime.Branch.isEqual(cc)) {
                // branch to FOUND_B
            }
            AsmRuntime.Memory.cli(ctx, "0(R4)", 'T', cc);
            if (AsmRuntime.Branch.isEqual(cc)) {
                // branch to PROCESS_T
            }
            AsmRuntime.Memory.cli(ctx, "0(R4)", 'X', cc);
            if (AsmRuntime.Branch.isEqual(cc)) {
                // branch to SKIP_X
            }
            AsmRuntime.Address.la(ctx, registers, 4, AsmRuntime.Address.ofBaseOffset(registers, 4, 1));
            // branch target: SCAN_LOOP
            // branch target: SCAN_LOOP
            AsmRuntime.Address.la(ctx, registers, 4, AsmRuntime.Address.ofBaseOffset(registers, 4, 10));
            // branch target: SCAN_LOOP
            // branch target: SCAN_LOOP
            AsmRuntime.Address.la(ctx, registers, 4, AsmRuntime.Address.ofBaseOffset(registers, 4, 9));
            // branch target: SCAN_LOOP
            // branch target: SCAN_LOOP
            AsmRuntime.Register.lr(registers, 5, 4);
            AsmRuntime.Address.la(ctx, registers, 4, AsmRuntime.Address.ofBaseOffset(registers, 4, 10));
            // branch target: SCAN_LOOP
            // branch target: SCAN_LOOP
            AsmRuntime.Register.ltr(registers, 5, 5, cc);
            if (AsmRuntime.Branch.isEqual(cc)) {
                // branch to SKIP_T_NO_B
            }
            AsmRuntime.Packed.pack(ctx, "WS_PACKED_AMT", "1(10,R4)", 8, 10, 15, 0, cc);
            AsmRuntime.Packed.zap(ctx, "WS_TAX_AMT", "WS_PACKED_AMT", 15, 0, cc);
            ctx.setDecimal("WS_TAX_AMT_MP_LITERAL", new java.math.BigDecimal("0.05"));
            AsmRuntime.Packed.mp(ctx, "WS_TAX_AMT", "WS_TAX_AMT_MP_LITERAL", 15, 0, cc);
            AsmRuntime.Packed.unpk(ctx, "WS_ZONED_TAX", "WS_TAX_AMT", 10, 8, 15, 0);
            AsmRuntime.Memory.oi(ctx, "WS_ZONED_TAX+9", 240, cc);
            AsmRuntime.Memory.mvc(ctx, "1(9,R5)", 9, "WS_ZONED_TAX+1");
            AsmRuntime.Address.la(ctx, registers, 4, AsmRuntime.Address.ofBaseOffset(registers, 4, 11));
            // branch target: SCAN_LOOP
            // branch target: SCAN_LOOP
        }
        // LABEL: WRITE_REC
        // EQU declaration: WRITE_REC EQU  *
        AsmRuntime.Memory.mvc(ctx, "OUT_RECORD", 100, "IN_RECORD");
        AsmRuntime.IO.put(ctx, "OUTFILE", "OUT_RECORD", cc);
        // branch target: READ_REC
        // LABEL: EOF_ROUTINE
        // EQU declaration: EOF_ROUTINE EQU *
        AsmRuntime.IO.close(ctx, cc, "INVSAM", "OUTFILE");
        return ModuleResult.rc(0, "Returned by translated RETURN");



    }
}
